import sys
import os
import subprocess
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QFileDialog, QDialog, QPlainTextEdit
from PyQt5.QtWidgets import QMainWindow
import inspect


class UiModuleMainWorkflow(object):
    def setupUi(self, moduleMainWorkflow):
        moduleMainWorkflow.setObjectName("moduleMainWorkflow")
        moduleMainWorkflow.resize(975, 703)
        self.centralwidget = QtWidgets.QWidget(moduleMainWorkflow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 110, 951, 531))
        self.tabWidget.setInputMethodHints(QtCore.Qt.ImhNone)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.frame = QtWidgets.QFrame(self.tab)
        self.frame.setGeometry(QtCore.QRect(10, 10, 931, 181))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 921, 170))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.checkBox_3 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout_2.addWidget(self.checkBox_3)
        self.checkBox_4 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_4.setObjectName("checkBox_4")
        self.verticalLayout_2.addWidget(self.checkBox_4)
        self.checkBox_2 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_2.addWidget(self.checkBox_2)
        self.checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_2.addWidget(self.checkBox)
        self.frame_2 = QtWidgets.QFrame(self.tab)
        self.frame_2.setGeometry(QtCore.QRect(10, 210, 931, 161))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.frame_2)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 921, 141))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.frame_2.raise_()
        self.frame.raise_()
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.frame_3 = QtWidgets.QFrame(self.tab_2)
        self.frame_3.setGeometry(QtCore.QRect(10, 10, 931, 171))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.frame_3)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(0, 0, 931, 170))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_5.addWidget(self.label_13)
        self.label_15 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_5.addWidget(self.label_15)
        self.radioButton_4 = QtWidgets.QRadioButton(self.verticalLayoutWidget_5)
        self.radioButton_4.setObjectName("radioButton_4")
        self.verticalLayout_5.addWidget(self.radioButton_4)
        self.radioButton_3 = QtWidgets.QRadioButton(self.verticalLayoutWidget_5)
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout_5.addWidget(self.radioButton_3)
        self.radioButton_2 = QtWidgets.QRadioButton(self.verticalLayoutWidget_5)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout_5.addWidget(self.radioButton_2)
        self.frame_4 = QtWidgets.QFrame(self.tab_2)
        self.frame_4.setGeometry(QtCore.QRect(10, 210, 931, 171))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.frame_4)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(0, 0, 931, 170))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_24 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_10.addWidget(self.label_24)
        self.label_25 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_10.addWidget(self.label_25)
        self.radioButton_5 = QtWidgets.QRadioButton(self.verticalLayoutWidget_7)
        self.radioButton_5.setObjectName("radioButton_5")
        self.verticalLayout_10.addWidget(self.radioButton_5)
        self.radioButton_6 = QtWidgets.QRadioButton(self.verticalLayoutWidget_7)
        self.radioButton_6.setObjectName("radioButton_6")
        self.verticalLayout_10.addWidget(self.radioButton_6)
        self.radioButton_7 = QtWidgets.QRadioButton(self.verticalLayoutWidget_7)
        self.radioButton_7.setObjectName("radioButton_7")
        self.verticalLayout_10.addWidget(self.radioButton_7)
        self.radioButton_8 = QtWidgets.QRadioButton(self.verticalLayoutWidget_7)
        self.radioButton_8.setObjectName("radioButton_8")
        self.verticalLayout_10.addWidget(self.radioButton_8)
        self.frame_5 = QtWidgets.QFrame(self.tab_2)
        self.frame_5.setGeometry(QtCore.QRect(10, 410, 931, 81))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.frame_5)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 931, 81))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_16 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_7.addWidget(self.label_16)
        self.label_23 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_7.addWidget(self.label_23)
        self.horizontalLayout_4.addLayout(self.verticalLayout_7)
        self.pushButton_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_3.setCheckable(False)
        self.pushButton_3.setChecked(False)
        self.pushButton_3.setEnabled(False)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_4.addWidget(self.pushButton_3)
        self.frame_4.raise_()
        self.frame_3.raise_()
        self.frame_5.raise_()
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_17 = QtWidgets.QLabel(self.tab_3)
        self.label_17.setGeometry(QtCore.QRect(330, 0, 244, 49))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.tab_3)
        self.label_18.setGeometry(QtCore.QRect(10, 0, 244, 49))
        self.label_18.setObjectName("label_18")
        self.label_27 = QtWidgets.QLabel(self.tab_3)
        self.label_27.setGeometry(QtCore.QRect(630, 0, 244, 49))
        self.label_27.setObjectName("label_27")
        self.frame_6 = QtWidgets.QFrame(self.tab_3)
        self.frame_6.setGeometry(QtCore.QRect(10, 50, 931, 451))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.frame_6)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 931, 452))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_9 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_6.addWidget(self.label_9)
        self.label_12 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_6.addWidget(self.label_12)
        self.label_11 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_6.addWidget(self.label_11)
        self.label_14 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_6.addWidget(self.label_14)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.pushButton_5 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_3.addWidget(self.pushButton_5)
        self.verticalLayout_9.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton_4 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_8.addWidget(self.pushButton_4)
        self.pushButton_4.setEnabled(False)
        self.pushButton_8 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_8.addWidget(self.pushButton_8)
        self.pushButton_8.setEnabled(False)
        self.verticalLayout_9.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_5.addWidget(self.pushButton_6)
        self.pushButton_6.setEnabled(False)
        self.verticalLayout_9.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_6.addWidget(self.pushButton_7)
        self.pushButton_7.setEnabled(False)
        self.verticalLayout_9.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_2.addLayout(self.verticalLayout_9)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_19 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_8.addWidget(self.label_19)
        self.label_20 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_8.addWidget(self.label_20)
        self.label_21 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_8.addWidget(self.label_21)
        self.label_22 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_8.addWidget(self.label_22)
        self.horizontalLayout_2.addLayout(self.verticalLayout_8)
        self.frame_6.raise_()
        self.label_17.raise_()
        self.label_18.raise_()
        self.label_27.raise_()
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(251, 0, 721, 101))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 231, 91))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("sindri_logo.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        moduleMainWorkflow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(moduleMainWorkflow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 975, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        moduleMainWorkflow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(moduleMainWorkflow)
        self.statusbar.setObjectName("statusbar")
        moduleMainWorkflow.setStatusBar(self.statusbar)
        self.actionSave = QtWidgets.QAction(moduleMainWorkflow)
        self.actionSave.setObjectName("actionSave")
        self.actionOpen = QtWidgets.QAction(moduleMainWorkflow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionNew = QtWidgets.QAction(moduleMainWorkflow)
        self.actionNew.setObjectName("actionNew")
        self.actionAbout_Welding_Workbench = QtWidgets.QAction(moduleMainWorkflow)
        self.actionAbout_Welding_Workbench.setObjectName("actionAbout_Welding_Workbench")
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionNew)
        self.menuHelp.addAction(self.actionAbout_Welding_Workbench)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(moduleMainWorkflow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(moduleMainWorkflow)

    def retranslateUi(self, moduleMainWorkflow):
        _translate = QtCore.QCoreApplication.translate
        moduleMainWorkflow.setWindowTitle(_translate("moduleMainWorkflow", "moduleMainWorkflow"))
        self.label_2.setText(_translate("moduleMainWorkflow", "SIMULATION OBJECTIVES "))
        self.label.setText(_translate("moduleMainWorkflow", "What is the main purpose of your weld simulation?"))
        self.checkBox_3.setText(_translate("moduleMainWorkflow", "Engineering scale defect analysis"))
        self.checkBox_4.setText(_translate("moduleMainWorkflow", "Understanding Microstructural and degradation conditions in the weld"))
        self.checkBox_2.setText(_translate("moduleMainWorkflow", "Optimisation of welding procedures"))
        self.checkBox.setText(_translate("moduleMainWorkflow", "Other"))
        self.label_3.setText(_translate("moduleMainWorkflow", "SUGGESTED ACTIVITY"))
        self.label_7.setText(_translate("moduleMainWorkflow", "Info to user"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("moduleMainWorkflow", "Tab 1"))
        self.label_13.setText(_translate("moduleMainWorkflow", "AS WELDED RESIDUAL STRESS PROFILES"))
        self.label_15.setText(_translate("moduleMainWorkflow", "How well do you need to know your residual stress distribution?"))
        self.radioButton_4.setText(_translate("moduleMainWorkflow", "Rough distribution (conservative estimate)"))
        self.radioButton_3.setText(_translate("moduleMainWorkflow", "Detailed distribution (less conservative estimate)"))
        self.radioButton_2.setText(_translate("moduleMainWorkflow", "Detailed distribution (least conservative estimate)"))
        self.label_16.setText(_translate("moduleMainWorkflow", "SUGGESTED ACTION"))
        self.label_23.setText(_translate("moduleMainWorkflow", "... Make selections above...."))
        self.pushButton_3.setText(_translate("moduleMainWorkflow", "Run FE Model"))
        self.label_24.setText(_translate("moduleMainWorkflow", "POST WELD HEAT TREATMENT RESIDUAL STRESS PROFILES"))
        self.label_25.setText(_translate("moduleMainWorkflow", "How well do you need to know your residual stress distribution?"))
        self.radioButton_5.setText(_translate("moduleMainWorkflow", "Rough distribution (conservative estimate)"))
        self.radioButton_6.setText(_translate("moduleMainWorkflow", "Detailed distribution (less conservative estimate)"))
        self.radioButton_7.setText(_translate("moduleMainWorkflow", "Detailed distribution (least conservative estimate)"))
        self.radioButton_8.setText(_translate("moduleMainWorkflow", "Not Applicable"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("moduleMainWorkflow", "Tab2"))
        self.label_9.setText(_translate("moduleMainWorkflow", "DEFINE MODEL"))
        self.label_12.setText(_translate("moduleMainWorkflow", "HEAT SOURCE CALIBRATION"))
        self.label_11.setText(_translate("moduleMainWorkflow", "METALLURGICAL MODELLING"))
        self.label_14.setText(_translate("moduleMainWorkflow", "MECHANICAL MODELLING"))
        self.pushButton_2.setText(_translate("moduleMainWorkflow", "Pick from catalog"))
        self.pushButton_4.setText(_translate("moduleMainWorkflow", "Heat source module"))
        self.pushButton_5.setText(_translate("moduleMainWorkflow", "Load Model"))
        self.pushButton_8.setText(_translate("moduleMainWorkflow", "Load Results"))
        self.pushButton_6.setText(_translate("moduleMainWorkflow", "Metallurgical module"))
        self.pushButton_7.setText(_translate("moduleMainWorkflow", "Run post-processing"))
        self.label_19.setText(_translate("moduleMainWorkflow", "User Selection Update 1"))
        self.label_20.setText(_translate("moduleMainWorkflow", "User Selection Update 2"))
        self.label_21.setText(_translate("moduleMainWorkflow", "User Selection Update 3"))
        self.label_22.setText(_translate("moduleMainWorkflow", "User Selection Update 4"))
        self.label_17.setText(_translate("moduleMainWorkflow", "INPUTS"))
        self.label_18.setText(_translate("moduleMainWorkflow", "Flowchart"))
        self.label_27.setText(_translate("moduleMainWorkflow", "User selection"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("moduleMainWorkflow", "Tab 3"))
        self.label_5.setText(_translate("moduleMainWorkflow", "Welcome to the Welding Workbench..."))
        self.label_4.setText(_translate("moduleMainWorkflow", "The purpose of this tool is to help you perform appropriate welding simulations"))
        self.pushButton.setText(_translate("moduleMainWorkflow", "Refer to ISO 18166:2016"))
        self.menuFile.setTitle(_translate("moduleMainWorkflow", "File"))
        self.menuHelp.setTitle(_translate("moduleMainWorkflow", "Help"))
        self.actionSave.setText(_translate("moduleMainWorkflow", "Save..."))
        self.actionOpen.setText(_translate("moduleMainWorkflow", "Open..."))
        self.actionNew.setText(_translate("moduleMainWorkflow", "New..."))
        self.actionAbout_Welding_Workbench.setText(_translate("moduleMainWorkflow", "About Welding Workbench..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    moduleMainWorkflow = QtWidgets.QMainWindow()
    ui = UiModuleMainWorkflow()
    ui.setupUi(moduleMainWorkflow)
    moduleMainWorkflow.show()
    sys.exit(app.exec_())

