# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'moduleMatProp.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class UiModuleMaterialProp(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(899, 679)
        self.W = QtWidgets.QLabel(Form)
        self.W.setGeometry(QtCore.QRect(460, 0, 74, 18))
        self.W.setObjectName("W")
        self.W2_label = QtWidgets.QLabel(Form)
        self.W2_label.setGeometry(QtCore.QRect(470, 300, 151, 18))
        self.W2_label.setObjectName("W2_label")
        self.P = QtWidgets.QLabel(Form)
        self.P.setGeometry(QtCore.QRect(10, 0, 74, 18))
        self.P.setObjectName("P")
        self.button_remove3 = QtWidgets.QPushButton(Form)
        self.button_remove3.setGeometry(QtCore.QRect(570, 240, 89, 25))
        self.button_remove3.setObjectName("button_remove3")
        self.button_add2 = QtWidgets.QPushButton(Form)
        self.button_add2.setGeometry(QtCore.QRect(20, 560, 89, 25))
        self.button_add2.setObjectName("button_add2")
        self.P2_label = QtWidgets.QLabel(Form)
        self.P2_label.setGeometry(QtCore.QRect(20, 300, 151, 18))
        self.P2_label.setObjectName("P2_label")
        self.button_remove2 = QtWidgets.QPushButton(Form)
        self.button_remove2.setGeometry(QtCore.QRect(120, 560, 89, 25))
        self.button_remove2.setObjectName("button_remove2")
        self.W2 = QtWidgets.QComboBox(Form)
        self.W2.setGeometry(QtCore.QRect(470, 320, 201, 25))
        self.W2.setObjectName("W2")
        self.W2.addItem("")
        self.W2.addItem("")
        self.button_add1 = QtWidgets.QPushButton(Form)
        self.button_add1.setGeometry(QtCore.QRect(20, 240, 89, 25))
        self.button_add1.setObjectName("button_add1")
        self.button_remove1 = QtWidgets.QPushButton(Form)
        self.button_remove1.setGeometry(QtCore.QRect(120, 240, 89, 25))
        self.button_remove1.setObjectName("button_remove1")
        self.split = QtWidgets.QFrame(Form)
        self.split.setGeometry(QtCore.QRect(426, -10, 20, 651))
        self.split.setFrameShape(QtWidgets.QFrame.VLine)
        self.split.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.split.setObjectName("split")
        self.Table_P2 = QtWidgets.QTableWidget(Form)
        self.Table_P2.setGeometry(QtCore.QRect(20, 360, 391, 190))
        self.Table_P2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.Table_P2.setAlternatingRowColors(False)
        self.Table_P2.setShowGrid(True)
        self.Table_P2.setRowCount(0)
        self.Table_P2.setColumnCount(2)
        self.Table_P2.setObjectName("Table_P2")
        item = QtWidgets.QTableWidgetItem()
        self.Table_P2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table_P2.setHorizontalHeaderItem(1, item)
        self.Table_P2.horizontalHeader().setCascadingSectionResizes(True)
        #self.Table_P2.horizontalHeader().setDefaultSectionSize(190)
        self.Table_P2.setColumnWidth(0,125)
        self.Table_P2.setColumnWidth(1,225)
        self.Table_P2.horizontalHeader().setMinimumSectionSize(32)
        self.Table_P1 = QtWidgets.QTableWidget(Form)
        self.Table_P1.setGeometry(QtCore.QRect(20, 40, 391, 190))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Table_P1.sizePolicy().hasHeightForWidth())
        self.Table_P1.setSizePolicy(sizePolicy)
        self.Table_P1.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.Table_P1.setAlternatingRowColors(False)
        self.Table_P1.setShowGrid(True)
        self.Table_P1.setRowCount(0)
        self.Table_P1.setColumnCount(2)
        self.Table_P1.setObjectName("Table_P1")
        item = QtWidgets.QTableWidgetItem()
        self.Table_P1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table_P1.setHorizontalHeaderItem(1, item)
        self.Table_P1.horizontalHeader().setCascadingSectionResizes(True)
        #self.Table_P1.horizontalHeader().setDefaultSectionSize(190)
        self.Table_P1.setColumnWidth(0,125)
        self.Table_P1.setColumnWidth(1,225)
        self.Table_P1.horizontalHeader().setMinimumSectionSize(32)
        self.button_remove4 = QtWidgets.QPushButton(Form)
        self.button_remove4.setGeometry(QtCore.QRect(570, 560, 89, 25))
        self.button_remove4.setObjectName("button_remove4")
        self.Table_W1 = QtWidgets.QTableWidget(Form)
        self.Table_W1.setGeometry(QtCore.QRect(470, 40, 391, 190))
        self.Table_W1.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.Table_W1.setAlternatingRowColors(False)
        self.Table_W1.setShowGrid(True)
        self.Table_W1.setRowCount(0)
        self.Table_W1.setColumnCount(2)
        self.Table_W1.setObjectName("Table_W1")
        item = QtWidgets.QTableWidgetItem()
        self.Table_W1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table_W1.setHorizontalHeaderItem(1, item)
        self.Table_W1.horizontalHeader().setCascadingSectionResizes(True)
        #self.Table_W1.horizontalHeader().setDefaultSectionSize(190)
        self.Table_W1.setColumnWidth(0,125)
        self.Table_W1.setColumnWidth(1,225)
        self.Table_W1.horizontalHeader().setMinimumSectionSize(32)
        self.Table_W2 = QtWidgets.QTableWidget(Form)
        self.Table_W2.setGeometry(QtCore.QRect(470, 360, 391, 190))
        self.Table_W2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.Table_W2.setAlternatingRowColors(False)
        self.Table_W2.setShowGrid(True)
        self.Table_W2.setRowCount(0)
        self.Table_W2.setColumnCount(2)
        self.Table_W2.setObjectName("Table_W2")
        item = QtWidgets.QTableWidgetItem()
        self.Table_W2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table_W2.setHorizontalHeaderItem(1, item)
        self.Table_W2.horizontalHeader().setCascadingSectionResizes(True)
        #self.Table_W2.horizontalHeader().setDefaultSectionSize(190)
        self.Table_W2.setColumnWidth(0,125)
        self.Table_W2.setColumnWidth(1,225)
        self.Table_W2.horizontalHeader().setMinimumSectionSize(32)
        self.button_add4 = QtWidgets.QPushButton(Form)
        self.button_add4.setGeometry(QtCore.QRect(470, 560, 89, 25))
        self.button_add4.setObjectName("button_add4")
        self.button_add3 = QtWidgets.QPushButton(Form)
        self.button_add3.setGeometry(QtCore.QRect(470, 240, 89, 25))
        self.button_add3.setObjectName("button_add3")
        self.P2 = QtWidgets.QComboBox(Form)
        self.P2.setGeometry(QtCore.QRect(20, 320, 201, 25))
        self.P2.setObjectName("P2")
        self.P2.addItem("")
        self.P2.addItem("")
        self.finish = QtWidgets.QPushButton(Form)
        self.finish.setGeometry(QtCore.QRect(740, 600, 95, 26))
        self.finish.setObjectName("finish")
        self.button_save = QtWidgets.QPushButton(Form)
        self.button_save.setGeometry(QtCore.QRect(620, 600, 95, 26))
        self.button_save.setObjectName("button_apply")
        self.button_save.setEnabled(False)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.W.setText(_translate("Form", "Weld"))
        self.W2_label.setText(_translate("Form", "Second Parameter:"))
        self.P.setText(_translate("Form", "Parent"))
        self.button_remove3.setText(_translate("Form", "Remove"))
        self.button_add2.setText(_translate("Form", "Add"))
        self.P2_label.setText(_translate("Form", "Second Parameter:"))
        self.button_remove2.setText(_translate("Form", "Remove"))
        self.W2.setItemText(0, _translate("Form", "Thermal Diffusivity"))
        self.W2.setItemText(1, _translate("Form", "Enthalpy"))
        self.button_add1.setText(_translate("Form", "Add"))
        self.button_remove1.setText(_translate("Form", "Remove"))
        item = self.Table_P2.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Temperature (C)"))
        item = self.Table_P2.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Thermal Diffusivity (mm²/s)"))
        item = self.Table_P1.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Temperature (C)"))
        item = self.Table_P1.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Thermal Conductivity (W/mK)"))
        self.button_remove4.setText(_translate("Form", "Remove"))
        item = self.Table_W1.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Temperature (C)"))
        item = self.Table_W1.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Thermal Conductivity (W/mK)"))
        item = self.Table_W2.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Temperature (C)"))
        item = self.Table_W2.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Thermal Diffusivity (mm²/s)"))
        self.button_add4.setText(_translate("Form", "Add"))
        self.button_add3.setText(_translate("Form", "Add"))
        self.P2.setItemText(0, _translate("Form", "Thermal Diffusivity"))
        self.P2.setItemText(1, _translate("Form", "Enthalpy"))
        self.finish.setText(_translate("Form", "Ok"))
        self.button_save.setText(_translate("Form", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = UiModuleMaterialProp()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

